const PROJDATA = [
  {
    name: "Amazon Clone",
    img: "https://cdn.statically.io/img/sudham.tk/f=auto/images/amazon-clone.jpg",
    tag: "react + firebase",
    desc: "This is a clone of AMAZON.COM with add to cart,login,checkout & payment with stripe functionality! Made with React.js and Firebase.",
    link: "https://amazon-clone.sudham.tk/",
  },
  {
    name: "Google Clone",
    img: "https://cdn.statically.io/img/sudham.tk/f=auto/images/google-clone.jpg",
    tag: "html + css",
    desc: "Mobile responsive Google UI Clone using HTML5 and Vanilla CSS3",
    link: "https://google-clone.sudham.tk",
  },
  {
    name: "Cleaner Essays",
    img: "https://cdn.statically.io/og/theme=dark/Paul%20Graham's%20essays%20made%20cleaner.jpg",
    tag: "react + flask",
    desc: "<a id='#paul' href='https://paulgraham.com/essays'>paulgraham.com</a> but made cleaner and easier to read. His essays are brilliant but hard to read, hence this!",
    link: "https://paulgraham.netlify.app",
  },
  {
    name: "MockGen",
    img: "https://cdn.statically.io/og/theme=dark/Generate%20beautiful%20mockups.jpg",
    tag: "python - flask",
    desc: "Wanted to have clean mockups of your side projects than bare screenshots? You can now generate beautiful mockups just from website url. WORK IN PROGRESS",
    link: "#",
  },
  {
    name: "Diwali Greeting Generator",
    img: "https://cdn.statically.io/img/sudham.tk/f=auto/images/diwali-gg.jpg",
    tag: "python - flask",
    desc: "This project is made on Diwali for people to generate diwali greetings, just a quick one-day hack ;)",
    link: "https://diwali-gg.sudham.tk/",
  },
  {
    name: "Upwork Job Scraper",
    img: "https://cdn.statically.io/og/theme=dark/Browser%20jobs%20right%20from%20your%20CLI.jpg",
    tag: "python",
    desc: "Opening upwork.com always to check for new jobs is a tedious task, so created this script that lets me browse jobs right from CLI",
    link: "https://github.com/sudhamjayanthi/upwork-job-scraper",
  },
  {
    name: "My CRUD Blog",
    img: "https://cdn.statically.io/img/sudham.tk/f=auto/images/blog.jpg",
    tag: "python - flask",
    desc: "A dynamic blog with CRUD functionality. A fun side project built while learning Flask.",
    link: "https://myblog.sudham.tk/",
  },
  {
    name: "Simple Inventory Search Addon",
    img: "https://cdn.statically.io/img/sudham.tk/f=auto/images/shopping-list.jpg",
    tag: "python - flask",
    desc: "You can search from inventory and then add/delete the products & export as excel. Built for my first client.",
    link: "https://shoplist.sudham.tk/",
  },
  {
    name: "ZeroCastinate",
    img: "https://cdn.statically.io/img/sudham.tk/f=auto/images/zerocastinate.jpg",
    tag: "react + firebase",
    desc: "Yet another todo-list app! Built to sharpen my skills",
    link: "https://todo.sudham.tk/",  
  },
];
